import importlib
from pathlib import Path

import pytest


def _write_minimal_pptx(path: Path) -> None:
    # Keep deps minimal: python-pptx is already in requirements.
    from pptx import Presentation

    prs = Presentation()
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Test deck"
    slide.placeholders[1].text = "Hello from tests"
    prs.save(str(path))


@pytest.fixture()
def app_client(tmp_path, monkeypatch):
    # Configure app via environment variables so we don't depend on any local config files.
    monkeypatch.setenv("OPENAI_API_KEY", "test-key")
    monkeypatch.setenv("HOST_INPUT_PATH", str(tmp_path / "input"))
    monkeypatch.setenv("HOST_OUTPUT_PATH", str(tmp_path / "output"))
    monkeypatch.setenv("HOST_COPY_PATH", str(tmp_path / "copies"))

    # Import after env is set (module-level paths are computed at import time).
    import note_maker.server as server

    importlib.reload(server)

    # Patch OpenAI call to avoid external requests.
    import note_maker.core as core

    def fake_generate_note_from_text(text: str, model_name: str, language_key: str) -> str:
        assert text.strip()
        return "# Test note\n\nGenerated by smoke test."

    core.generate_note_from_text = fake_generate_note_from_text

    from fastapi.testclient import TestClient

    return TestClient(server.app)


def test_healthz(app_client):
    res = app_client.get("/healthz")
    assert res.status_code == 200
    assert res.json() == {"status": "ok"}


def test_options(app_client):
    res = app_client.get("/api/options")
    assert res.status_code == 200
    payload = res.json()
    assert "models" in payload
    assert "languages" in payload
    assert payload["config"]["needsSetup"] is False


def test_generate_smoke(app_client, tmp_path):
    pptx_path = tmp_path / "sample.pptx"
    _write_minimal_pptx(pptx_path)

    with pptx_path.open("rb") as fh:
        res = app_client.post(
            "/api/generate",
            files={
                "file": (
                    "sample.pptx",
                    fh,
                    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                )
            },
            data={
                "model": "gpt-5.1",
                "language": "nynorsk",
                "copy_source": "false",
                "existing_path": "",
                "output_dir": "",
                "copy_dir": "",
            },
        )

    assert res.status_code == 200, res.text
    payload = res.json()
    assert payload["noteText"].startswith("# Test note")

    note_path = Path(payload["notePath"])
    assert note_path.exists()
